# Generated by Django 4.2.18 on 2025-02-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_pessoa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.cidade'),
        ),
    ]
